name: CI
on:
  workflow_run:
    workflows: [ "Run Tests" ]
    branches: [ master ]
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: |
          go get github.com/mitchellh/gox
          go get github.com/tcnksm/ghr
      - uses: actions/checkout@v2
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          gox -parallel 4 -osarch="linux/amd64 darwin/amd64 linux/arm windows/amd64" -ldflags="-extldflags '-static' -s -w -X github.com/saitho/git-file-webserver/config.VERSION=${{steps.semrel.outputs.version}}" -output="bin/{{.Dir}}_v${{steps.semrel.outputs.version}}_{{.OS}}_{{.Arch}}" .
          cd bin/ && shasum -a 256 * > ./git-file-webserver_v${{steps.semrel.outputs.version}}_checksums.txt && cd -
        if: steps.semrel.outputs.version != ''
        env:
          CGO_ENABLED: 0
      - run: ghr v${{ steps.semrel.outputs.version }} bin/
        if: steps.semrel.outputs.version != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
